name: Cypress Tests

on:
  push:
    branches:
      - main  # Zmień to na nazwę głównej gałęzi repozytorium

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run
